### ISSUE TITLE
Site title

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-usu.org#1]
The site doesn't appear to have a title and just shows the site URL in the browser tab.

Please change the site title to NAM

<img width="1165" alt="Screen Shot 2022-01-13 at 11 32 10 AM" src="https://user-images.githubusercontent.com/8645379/149396869-a8c94df6-8f63-425e-9c01-2eabeb0cc6e1.png">

**Comment by MattReimer** [comment]
The site title needed a new gatsby plugin. It is now a combination of the name from `gatsby-config.js` and the `title:` field from the frontmatter. We can change this behaviour easily

@philipbaileynar run `yarn install` to make sure you have the new plugin

**Comment by philipbaileynar** [comment]
Works for me locally. And I see it working on published site! Thanks.
